### ISSUE TITLE
Error: No matching bindings found for serviceIdentifier: Symbol()

### ISSUE THREAD

**Issue by DoDoSt** [CKGrafico/inversify-props#25]
In production build I get the following error with injecting a service in a Vue component
`vue.runtime.esm.js:1888 Error: No matching bindings found for serviceIdentifier: Symbol(TestService)`.

In dev build everything works. 

Production build with: 
`vue-cli-service build`

Dev build with:
`vue-cli-service serve` or `vue-cli-service build --mode development`

I made a simple project to show my issue: 

[TestVueProject.zip](https://github.com/CKGrafico/inversify-props/files/4671756/TestVueProject.zip)

**Comment by CKGrafico** [comment]
Hello probably this will help https://github.com/CKGrafico/inversify-props#how-to-configure-uglify-or-terser

**Comment by DoDoSt** [comment]
Good idea! I didn't think about that the class names would be changed during productive construction. Thanks for the hint.

**Comment by CKGrafico** [comment]
Sorry probably is not well documented, I accept suggestions

**Comment by NavidMitchell** [comment]
I am having this problem after upgrading to 2.2.6 from 1.4.9. It seems to only happen if I inject more than one dependency into a vue component. If I down grade to 1.4.9 everything works as expected.

**Comment by CKGrafico** [comment]
Are you decorating your classes with @injectable? because is not required anymore

**Comment by NavidMitchell** [comment]
I was initially but I saw the other issue about that so I removed injectable from all of my classes and still was getting the same error.

**Comment by CKGrafico** [comment]
Can you share a sandbox to reproduce?

**Comment by LukasWillin** [comment]
Sry for bumping this in 2025 😅
I just bashed my head in for quite some time and thought I'd mention my solution.

We had `configureWebpack`-options set as mentioned in the docs. Yet, the production builds suddenly started failing after upgrading some packages stating `Error: No matching bindings found for serviceIdentifier: Symbol()`. It was easy to verify by inspecting the mappings in `{ cid }` that some were being minified even though we told terser not to.

Anyhow. Switching to the `chainWebpack`-option did the trick:

```js
module.exports = {
    ...
    chainWebpack: config => 
    {
        if (is_env_development)
            config.devtool("source-map");

        config.optimization
            .minimizer("terser")
            .tap(args => 
            {
                const options = args[0];
                const { terserOptions } = options;
                terserOptions.keep_classnames = true;
                terserOptions.keep_fnames = true;
                terserOptions.mangle = {
                    ...terserOptions.mangle, // Preserve default options from vue-cli
                    properties: false, // mangle all property names
                };
                return args;
            })
    },
    ...
}
```

Sadly I cannot really tell what the issue was in the end, even using `vue inspect` for both `dev` and `prod` builds didn't give me any real clues. We probably just have an unholy combination of library versions.

**Comment by CKGrafico** [comment]
thanks for trying in 2025 :)
